name: lando-mongo-6
services:
  defaults:
    type: mongo:6.0
  patch:
    type: mongo:6.0.5
tooling:
  mongo:
    service: defaults

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/mongo": ./../../
