name: lando-mongo-3
services:
  defaults:
    type: mongo:3.7
  patch:
    type: mongo:3.6.23
tooling:
  mongo:
    service: defaults

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/mongo": ../..
