name: lando-mongo-4
services:
  defaults:
    type: mongo:4.4
  patch:
    type: mongo:4.4.11
tooling:
  mongo:
    service: defaults

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/mongo": ../..
