name: lando-mongo-8
services:
  defaults:
    type: mongo:8.0
  patch:
    type: mongo:8.0.9
tooling:
  mongosh:
    service: defaults

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/mongo": ../..
