name: lando-mongo
services:
  custom:
    type: mongo:3.6
    portforward: true
    config:
      database: custom.conf

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/mongo": ../..
